### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by qwertukg** [qwertukg/SeleniumBuilder#3]
@stalexxx Please improve functionality for original repo. It will be useful for me too

**Comment by stalexxx** [comment]
pull request created

**Comment by qwertukg** [comment]
Approved! thanks a lot

**Comment by qwertukg** [comment]
@stalexxx are u use `--headles` for remote (CD) test running? if so plz text me on email, try to implement DI testing to. Have some questions about it. Thanks
