### ISSUE TITLE
Publish to Bintray/JCenter or Maven?

### ISSUE THREAD

**Issue by checketts** [qwertukg/SeleniumBuilder#6]
Is this library published to some repository for consumption?

**Comment by qwertukg** [comment]
Still not. But u can fix it, it will be really usefull for all. 
Also u can use https://jitpack.io

Thanks

**Comment by checketts** [comment]
Thanks for the update. I think I'll work on combining the best of this repo, Balin, and the other project I saw into a complete DSL.

Thanks for posting your code, it has inspired some great ideas!

**Comment by qwertukg** [comment]
@checketts, you should check this https://github.com/petrbalat/kd4smt too. 
Keep me in touch plz

**Comment by checketts** [comment]
Funny you should mention that repo. If you look at the [recent commits](https://github.com/petrbalat/kd4smt/commits/master), you'll see that I just contributed some major overhauls on that repo. :D
